In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
dataset = pd.read_csv('house_price_regression_dataset.csv')
x=dataset.iloc[1:11, :-1].values
y=dataset.iloc[1:11, 4].values


In [3]:
print(x)
print(y)

[[4.27200000e+03 3.00000000e+00 3.00000000e+00 2.01600000e+03
  4.75301385e+00 1.00000000e+00 6.00000000e+00]
 [3.59200000e+03 1.00000000e+00 2.00000000e+00 2.01600000e+03
  3.63482272e+00 0.00000000e+00 9.00000000e+00]
 [9.66000000e+02 1.00000000e+00 2.00000000e+00 1.97700000e+03
  2.73066688e+00 1.00000000e+00 8.00000000e+00]
 [4.92600000e+03 2.00000000e+00 1.00000000e+00 1.99300000e+03
  4.69907255e+00 0.00000000e+00 8.00000000e+00]
 [3.94400000e+03 5.00000000e+00 3.00000000e+00 1.99000000e+03
  2.47593004e+00 2.00000000e+00 8.00000000e+00]
 [3.67100000e+03 1.00000000e+00 2.00000000e+00 2.01200000e+03
  4.91196007e+00 0.00000000e+00 1.00000000e+00]
 [3.41900000e+03 1.00000000e+00 1.00000000e+00 1.97200000e+03
  2.80528141e+00 1.00000000e+00 1.00000000e+00]
 [6.30000000e+02 3.00000000e+00 3.00000000e+00 1.99700000e+03
  1.01428597e+00 1.00000000e+00 8.00000000e+00]
 [2.18500000e+03 4.00000000e+00 2.00000000e+00 1.98100000e+03
  3.94160438e+00 2.00000000e+00 5.00000000e+00]
 [1.269000

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# OneHotEncoder diterapkan ke kolom ke-3 (indeks 3)
columnTransformer = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [3])
    ], remainder='passthrough')

x = columnTransformer.fit_transform(x)


In [6]:
x = x[:, 1:]

In [7]:
x

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        4.27200000e+03, 3.00000000e+00, 3.00000000e+00, 4.75301385e+00,
        1.00000000e+00, 6.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.59200000e+03, 1.00000000e+00, 2.00000000e+00, 3.63482272e+00,
        0.00000000e+00, 9.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        9.66000000e+02, 1.00000000e+00, 2.00000000e+00, 2.73066688e+00,
        1.00000000e+00, 8.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.92600000e+03, 2.00000000e+00, 1.00000000e+00, 4.69907255e+00,
        0.000

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
regressor=LinearRegression()

In [10]:
x_train

array([[3.94400000e+03, 5.00000000e+00, 3.00000000e+00, 1.99000000e+03,
        2.47593004e+00, 2.00000000e+00, 8.00000000e+00],
       [1.26900000e+03, 2.00000000e+00, 2.00000000e+00, 2.00600000e+03,
        3.55503976e+00, 1.00000000e+00, 9.00000000e+00],
       [3.59200000e+03, 1.00000000e+00, 2.00000000e+00, 2.01600000e+03,
        3.63482272e+00, 0.00000000e+00, 9.00000000e+00],
       [3.41900000e+03, 1.00000000e+00, 1.00000000e+00, 1.97200000e+03,
        2.80528141e+00, 1.00000000e+00, 1.00000000e+00],
       [6.30000000e+02, 3.00000000e+00, 3.00000000e+00, 1.99700000e+03,
        1.01428597e+00, 1.00000000e+00, 8.00000000e+00],
       [4.92600000e+03, 2.00000000e+00, 1.00000000e+00, 1.99300000e+03,
        4.69907255e+00, 0.00000000e+00, 8.00000000e+00],
       [4.27200000e+03, 3.00000000e+00, 3.00000000e+00, 2.01600000e+03,
        4.75301385e+00, 1.00000000e+00, 6.00000000e+00],
       [3.67100000e+03, 1.00000000e+00, 2.00000000e+00, 2.01200000e+03,
        4.91196007e+00, 0

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [12]:
x_train

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.94400000e+03, 5.00000000e+00, 3.00000000e+00, 2.47593004e+00,
        2.00000000e+00, 8.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.26900000e+03, 2.00000000e+00, 2.00000000e+00, 3.55503976e+00,
        1.00000000e+00, 9.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.59200000e+03, 1.00000000e+00, 2.00000000e+00, 3.63482272e+00,
        0.00000000e+00, 9.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.41900000e+03, 1.00000000e+00, 1.00000000e+00, 2.80528141e+00,
        1.000

In [13]:
regressor.fit(x_train, y_train)

LinearRegression()

In [14]:
y_predict = regressor.predict(x_test)

In [15]:
x_test

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        9.66000000e+02, 1.00000000e+00, 2.00000000e+00, 2.73066688e+00,
        1.00000000e+00, 8.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.18500000e+03, 4.00000000e+00, 2.00000000e+00, 3.94160438e+00,
        2.00000000e+00, 5.00000000e+00]])

In [16]:
y_predict

array([2.57663934, 3.7610311 ])

In [17]:
y_test

array([2.73066688, 3.94160438])

In [18]:
print(regressor.coef_)
print(regressor.intercept_)

[ 4.44015484e-14 -5.55111512e-17 -1.40946079e-01  7.14757687e-02
 -8.57252126e-02  2.09477964e-01  6.51383318e-02  1.29000723e-02
  6.92334761e-05  1.31490203e-02  6.78887993e-02  9.01637014e-01
 -5.67452370e-02 -8.48941740e-03]
0.023423436807814113


### Coba

In [19]:
print(x_test.shape)

(2, 14)


In [20]:

databr=np.array([[821, 3, 2, 2001, 3.51066688, 0, 7],
                [3702, 5, 1, 1984, 1.78029125, 2, 6],
                [2102, 2, 1, 1984, 2.74521093, 1, 7],
                [966, 1, 2, 1977, 2.730666876, 1, 8]])




In [21]:
print(databr.shape)

(4, 7)


In [22]:
databr

array([[8.21000000e+02, 3.00000000e+00, 2.00000000e+00, 2.00100000e+03,
        3.51066688e+00, 0.00000000e+00, 7.00000000e+00],
       [3.70200000e+03, 5.00000000e+00, 1.00000000e+00, 1.98400000e+03,
        1.78029125e+00, 2.00000000e+00, 6.00000000e+00],
       [2.10200000e+03, 2.00000000e+00, 1.00000000e+00, 1.98400000e+03,
        2.74521093e+00, 1.00000000e+00, 7.00000000e+00],
       [9.66000000e+02, 1.00000000e+00, 2.00000000e+00, 1.97700000e+03,
        2.73066688e+00, 1.00000000e+00, 8.00000000e+00]])

In [23]:
# Menambahkan 7 fitur lagi (misal, diisi dengan nilai 0)
databr_extended = np.hstack([databr, np.zeros((databr.shape[0], 7))])

# Memprediksi dengan data yang sudah diperpanjang
y_predict = regressor.predict(databr_extended)

print(y_predict)

[142.91956017 142.3475726  142.12051502 141.54562368]
