In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle 

In [ ]:
dataset = pd.read_csv('house_price_regression_dataset.csv')
x=dataset.drop(columns=['House_Price']).values
y=dataset['House_Price'].values


In [ ]:
print(x)
print(y)

[[1.36000000e+03 2.00000000e+00 1.00000000e+00 ... 5.99636640e-01
  0.00000000e+00 5.00000000e+00]
 [4.27200000e+03 3.00000000e+00 3.00000000e+00 ... 4.75301385e+00
  1.00000000e+00 6.00000000e+00]
 [3.59200000e+03 1.00000000e+00 2.00000000e+00 ... 3.63482272e+00
  0.00000000e+00 9.00000000e+00]
 ...
 [2.60600000e+03 4.00000000e+00 2.00000000e+00 ... 4.05506679e+00
  0.00000000e+00 2.00000000e+00]
 [4.72300000e+03 5.00000000e+00 2.00000000e+00 ... 1.93092148e+00
  0.00000000e+00 7.00000000e+00]
 [3.26800000e+03 4.00000000e+00 2.00000000e+00 ... 3.10879025e+00
  2.00000000e+00 2.00000000e+00]]
[ 262382.8523  985260.8545  777977.3901  229698.9187 1041740.859
  879796.9835  814427.8614  703413.1109  173875.0372  504176.5061
  335332.5928  635097.3959  701133.8041  440726.2848  838719.4305
 1019192.661   735850.8123  234261.65    396246.3589  672852.052
  586086.5685  740174.0147  370167.0909  530824.1968  227515.3003
  652166.1424  745670.6371  513161.9512  432357.9061  434165.8966
  8096

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [ ]:
x

array([[1.36000000e+03, 2.00000000e+00, 1.00000000e+00, ...,
        5.99636640e-01, 0.00000000e+00, 5.00000000e+00],
       [4.27200000e+03, 3.00000000e+00, 3.00000000e+00, ...,
        4.75301385e+00, 1.00000000e+00, 6.00000000e+00],
       [3.59200000e+03, 1.00000000e+00, 2.00000000e+00, ...,
        3.63482272e+00, 0.00000000e+00, 9.00000000e+00],
       ...,
       [2.60600000e+03, 4.00000000e+00, 2.00000000e+00, ...,
        4.05506679e+00, 0.00000000e+00, 2.00000000e+00],
       [4.72300000e+03, 5.00000000e+00, 2.00000000e+00, ...,
        1.93092148e+00, 0.00000000e+00, 7.00000000e+00],
       [3.26800000e+03, 4.00000000e+00, 2.00000000e+00, ...,
        3.10879025e+00, 2.00000000e+00, 2.00000000e+00]])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
regressor=LinearRegression()

In [ ]:
x_train

array([[2.10300000e+03, 1.00000000e+00, 3.00000000e+00, ...,
        3.99330715e+00, 0.00000000e+00, 1.00000000e+01],
       [1.88400000e+03, 4.00000000e+00, 1.00000000e+00, ...,
        2.10545920e+00, 2.00000000e+00, 7.00000000e+00],
       [6.16000000e+02, 2.00000000e+00, 3.00000000e+00, ...,
        3.46137163e+00, 1.00000000e+00, 7.00000000e+00],
       ...,
       [2.40600000e+03, 5.00000000e+00, 2.00000000e+00, ...,
        9.30780746e-01, 1.00000000e+00, 1.00000000e+00],
       [1.51500000e+03, 2.00000000e+00, 1.00000000e+00, ...,
        1.02065593e+00, 1.00000000e+00, 3.00000000e+00],
       [6.25000000e+02, 3.00000000e+00, 1.00000000e+00, ...,
        2.38931914e+00, 0.00000000e+00, 2.00000000e+00]])

In [ ]:
x_train

array([[2.10300000e+03, 1.00000000e+00, 3.00000000e+00, ...,
        3.99330715e+00, 0.00000000e+00, 1.00000000e+01],
       [1.88400000e+03, 4.00000000e+00, 1.00000000e+00, ...,
        2.10545920e+00, 2.00000000e+00, 7.00000000e+00],
       [6.16000000e+02, 2.00000000e+00, 3.00000000e+00, ...,
        3.46137163e+00, 1.00000000e+00, 7.00000000e+00],
       ...,
       [2.40600000e+03, 5.00000000e+00, 2.00000000e+00, ...,
        9.30780746e-01, 1.00000000e+00, 1.00000000e+00],
       [1.51500000e+03, 2.00000000e+00, 1.00000000e+00, ...,
        1.02065593e+00, 1.00000000e+00, 3.00000000e+00],
       [6.25000000e+02, 3.00000000e+00, 1.00000000e+00, ...,
        2.38931914e+00, 0.00000000e+00, 2.00000000e+00]])

In [ ]:
regressor.fit(x_train, y_train)
fw = open('regresi1.pkl' , 'wb')
md = pickle.dump(regressor , fw)

In [ ]:
y_predict = regressor.predict(x_test)

In [ ]:
x_test

array([[3.40100000e+03, 5.00000000e+00, 3.00000000e+00, ...,
        3.54247262e+00, 1.00000000e+00, 5.00000000e+00],
       [3.78100000e+03, 2.00000000e+00, 1.00000000e+00, ...,
        3.16407579e+00, 0.00000000e+00, 9.00000000e+00],
       [4.34700000e+03, 3.00000000e+00, 1.00000000e+00, ...,
        4.23191405e+00, 1.00000000e+00, 3.00000000e+00],
       ...,
       [3.05700000e+03, 3.00000000e+00, 2.00000000e+00, ...,
        1.41874952e+00, 0.00000000e+00, 2.00000000e+00],
       [2.79600000e+03, 3.00000000e+00, 1.00000000e+00, ...,
        2.75214792e+00, 1.00000000e+00, 2.00000000e+00],
       [4.59700000e+03, 3.00000000e+00, 2.00000000e+00, ...,
        3.68077035e+00, 0.00000000e+00, 9.00000000e+00]])

In [ ]:
y_predict

array([ 784748.72845791,  797946.50559169,  917634.17718104,
        238229.99835762,  503563.52476977,  327149.68094066,
        509465.18094247,  429927.6794914 ,  930962.03488019,
        416856.77654862,  906103.88964089,  276254.20428414,
        365568.73831277,  816459.29055746,  717329.98485847,
        856086.78783584,  994075.00511594,  242674.68757536,
        834486.62595271,  561722.70689365,  880172.48979126,
        417526.46725996,  859380.61824219,  347575.12510853,
        357772.4198494 ,  174420.10966294,  723489.84278819,
        688443.5235438 ,  677763.35545487,  976957.77579039,
        414796.37157941,  529718.51851123,  824648.45189034,
        963427.91998069,  816961.37835262,  365240.23838739,
        711307.03922465,  731468.26381555,  891240.3215136 ,
        726808.47045762,  526323.86241203,  687499.17969409,
        444682.62384537,  631713.34112065,  703105.79532025,
        856652.78754574,  313857.9467433 ,  383755.89056343,
        786771.35402981,

In [ ]:
y_test

array([ 786584.6102,  792681.5184,  895675.5548,  239234.5743,
        510968.1407,  345655.7949,  513161.9512,  424712.5513,
        915005.2949,  415639.6454,  896600.4885,  284798.2135,
        377431.0644,  815811.6827,  705754.432 ,  866877.3524,
        985628.9692,  250101.5473,  838719.4305,  551967.8883,
        883819.0911,  427947.1031,  867445.4185,  342303.6893,
        354744.6306,  185557.6965,  735678.4622,  696709.4153,
        663568.5127,  985260.8545,  418003.1573,  525760.8806,
        806645.0449,  976049.1315,  824529.5721,  364016.4012,
        708003.0797,  738935.8194,  876992.6297,  731899.4356,
        539478.4032,  683723.1607,  470083.2904,  638451.4028,
        698124.6115,  877752.3422,  313266.8365,  355281.4185,
        786580.3015,  146020.4034,  262398.446 , 1015556.149 ,
        211038.8532,  914555.745 ,  312914.0031,  299226.7671,
        527544.9105,  797034.4255,  814843.6877,  348893.554 ,
        537770.4956,  583183.4309,  834105.7943,  47097

In [ ]:
print(regressor.coef_)
print(regressor.intercept_)

[  199.7890175  10062.46470437  7965.64347365  1002.26285842
 14966.6462566   4543.16872782   154.74291908]
-2027795.4572399473


### Membuat Data Baru

In [ ]:
#Square_Footage, Num_Bedrooms, Num_Bathrooms, Year_Built, Lot_Size, Garage_Size, Neighborhood_Quality, House_Price
databr=dataset.drop(columns=['House_Price']).sample(10)

In [ ]:
print(databr.shape)

(10, 7)


In [ ]:
databr

Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
997            2606             4              2        1962  4.055067   
913            3620             4              1        1978  2.228192   
124            3802             2              2        1975  3.995557   
567            4500             3              2        1954  4.539846   
436            4992             4              2        1960  4.257797   
735            3262             2              3        2015  0.894161   
888            4521             5              3        2008  4.562175   
388            4413             3              2        2002  4.750996   
537            4968             4              3        1994  0.840475   
968            4483             3              1        1971  1.723039   

     Garage_Size  Neighborhood_Quality  
997            0                     2  
913            0                     5  
124            2                     4  
567            0                     6  
436            1                    10  
735            1                     3  
888            2                     2  
388            1                     9  
537            1                     6  
968            1                     1

In [ ]:
opf = open('regresi1.pkl' , 'rb')
regres = pickle.load(opf)
y_pred = regres.predict(databr)

print(y_pred)

[ 576475.83232853  760254.49649649  816833.14898849  944670.15530047
 1059983.20215809  705887.82382591 1039880.04415694  983564.72902292
 1045466.02839072  911957.87139867]


C:\Users\ALIF RAMA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [ ]:
databr=np.array([[821, 3, 2, 2001, 3.51066688, 0, 7],
                [3702, 5, 1, 1984, 1.78029125, 2, 6],
                [2102, 2, 1, 1984, 2.74521093, 1, 7],
                [966, 1, 2, 1977, 2.730666876, 1, 8]])

In [ ]:
opf = open('regresi1.pkl' , 'rb')
regres = pickle.load(opf)
y_pred = regres.predict(databr)

print(y_pred)

[ 187970.22511589  745513.59760999  499167.53840532  212488.378567
  713048.13080708  430067.69251276  638740.45956162  131945.33474731
  792996.86689849 1009687.10844507]


### Simpan data

In [ ]:

# Nama kolom yang Anda inginkan
columns = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built', 
           'Lot_Size', 'Garage_Size', 'Neighborhood_Quality']

# Simpan databr ke dalam file CSV
databr_df = pd.DataFrame(databr, columns=columns)
databr_df['Prediksi'] = y_pred  # Menambahkan hasil prediksi sebagai kolom baru

# Simpan ke file CSV
databr_df.to_csv('databr_predictions.csv', index=False)

print("Data berhasil disimpan ke dalam 'databr_with_predictions.csv'.")


Data berhasil disimpan ke dalam 'databr_with_predictions.csv'.
