In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle 

In [2]:
dataset = pd.read_csv('winequality-red.csv')
x=dataset.drop(columns=['quality']).values
y=dataset['quality'].values


In [3]:
print(x)
print(y)

[[ 7.4    0.7    0.    ...  3.51   0.56   9.4  ]
 [ 7.8    0.88   0.    ...  3.2    0.68   9.8  ]
 [ 7.8    0.76   0.04  ...  3.26   0.65   9.8  ]
 ...
 [ 6.3    0.51   0.13  ...  3.42   0.75  11.   ]
 [ 5.9    0.645  0.12  ...  3.57   0.71  10.2  ]
 [ 6.     0.31   0.47  ...  3.39   0.66  11.   ]]
[5 5 5 ... 6 5 6]


In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [5]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
regressor=LinearRegression()

In [8]:
x_train

array([[ 9.9 ,  0.54,  0.45, ...,  3.39,  0.62,  9.4 ],
       [10.8 ,  0.26,  0.45, ...,  3.13,  0.54,  9.6 ],
       [ 9.9 ,  0.35,  0.55, ...,  3.26,  0.79, 10.6 ],
       ...,
       [ 7.9 ,  0.57,  0.31, ...,  3.29,  0.69,  9.5 ],
       [13.  ,  0.47,  0.49, ...,  3.3 ,  0.68, 12.7 ],
       [ 9.8 ,  0.98,  0.32, ...,  3.25,  0.48,  9.4 ]])

In [9]:
x_train

array([[ 9.9 ,  0.54,  0.45, ...,  3.39,  0.62,  9.4 ],
       [10.8 ,  0.26,  0.45, ...,  3.13,  0.54,  9.6 ],
       [ 9.9 ,  0.35,  0.55, ...,  3.26,  0.79, 10.6 ],
       ...,
       [ 7.9 ,  0.57,  0.31, ...,  3.29,  0.69,  9.5 ],
       [13.  ,  0.47,  0.49, ...,  3.3 ,  0.68, 12.7 ],
       [ 9.8 ,  0.98,  0.32, ...,  3.25,  0.48,  9.4 ]])

In [20]:
regressor.fit(x_train, y_train)
fw = open('regresiwine.pkl' , 'wb')
md = pickle.dump(regressor , fw)

In [11]:
y_predict = regressor.predict(x_test)

In [12]:
x_test 

array([[10.8  ,  0.47 ,  0.43 , ...,  3.17 ,  0.76 , 10.8  ],
       [ 8.1  ,  0.82 ,  0.   , ...,  3.36 ,  0.53 ,  9.6  ],
       [ 9.1  ,  0.29 ,  0.33 , ...,  3.26 ,  0.84 , 11.7  ],
       ...,
       [ 9.1  ,  0.34 ,  0.42 , ...,  3.18 ,  0.55 , 11.4  ],
       [ 9.1  ,  0.765,  0.04 , ...,  3.29 ,  0.54 ,  9.7  ],
       [ 8.2  ,  0.32 ,  0.42 , ...,  3.27 ,  0.55 , 12.3  ]])

In [13]:
y_predict

array([5.7829301 , 5.03619267, 6.59698929, 5.33912637, 5.93952898,
       5.0072068 , 5.39616171, 6.05211188, 4.86760343, 4.95067572,
       5.28580441, 5.41265269, 5.7057424 , 5.12921737, 5.52885206,
       6.38052412, 6.81012527, 5.73803346, 5.97618825, 5.08613415,
       6.34479863, 5.16400983, 5.64203971, 6.1462903 , 5.4817802 ,
       5.03391406, 5.18721293, 6.48783659, 5.33301372, 6.30458308,
       6.03452293, 5.82849303, 5.58503524, 5.28512701, 5.75656128,
       6.15273792, 5.14134479, 5.48228021, 6.38983359, 5.7901819 ,
       5.42936928, 6.04810414, 6.70159678, 6.60160183, 5.97253803,
       4.78890763, 5.49565005, 6.01881894, 5.48895041, 6.10824243,
       5.3126164 , 5.28492351, 5.76043226, 6.36081498, 5.7195388 ,
       5.26971928, 5.08498332, 5.31050693, 6.50895816, 5.44323413,
       5.16377401, 5.76427324, 6.0703837 , 6.28933679, 5.07315141,
       6.11874641, 5.35681067, 6.01343647, 6.12184268, 5.98547673,
       5.35327968, 5.4367731 , 5.06017324, 5.58939889, 5.62593

In [14]:
y_test

array([6, 5, 7, 6, 5, 6, 5, 6, 4, 5, 5, 5, 6, 5, 6, 6, 7, 5, 5, 4, 7, 6,
       6, 4, 6, 5, 5, 7, 5, 6, 5, 6, 5, 6, 7, 7, 5, 6, 6, 7, 5, 7, 6, 6,
       5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6,
       5, 5, 6, 6, 6, 6, 4, 6, 5, 6, 5, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 4, 5, 7, 6, 6, 5, 6, 5, 8, 6, 6, 6, 5, 5, 5, 5, 7, 5,
       6, 5, 7, 5, 6, 6, 6, 7, 6, 6, 5, 7, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6,
       6, 6, 6, 5, 6, 5, 8, 5, 6, 5, 6, 5, 4, 6, 7, 6, 5, 6, 6, 5, 5, 5,
       6, 6, 3, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 8, 5, 6,
       6, 7, 7, 5, 5, 7, 5, 6, 6, 4, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 7, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5,
       5, 5, 6, 6, 5, 6, 6, 6, 3, 6, 5, 5, 7, 6, 7, 6, 6, 7, 7, 6, 5, 6,
       5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 7, 5, 6, 5, 6,
       5, 4, 5, 5, 6, 7, 6, 5, 5, 4, 5, 6, 7, 6, 6, 7, 5, 7, 5, 6, 6, 5,
       5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6,

In [15]:
print(regressor.coef_)
print(regressor.intercept_)

[ 4.12835075e-02 -1.14952802e+00 -1.77927063e-01  2.78700036e-02
 -1.87340739e+00  2.68362616e-03 -2.77748370e-03 -3.15166657e+01
 -2.54486051e-01  9.24040106e-01  2.67797417e-01]
34.99871063155596


### Membuat Data Baru

In [16]:
#fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
databr=dataset.drop(columns=['quality']).sample(10)

In [17]:
print(databr.shape)

(10, 11)


In [18]:
databr

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
34              5.2             0.320         0.25             1.8      0.103   
1580            7.4             0.350         0.33             2.4      0.068   
786             9.9             0.350         0.41             2.3      0.083   
1004            8.2             0.430         0.29             1.6      0.081   
109             8.1             0.785         0.52             2.0      0.122   
182             7.2             0.730         0.02             2.5      0.076   
1435           10.2             0.540         0.37            15.4      0.214   
243            15.0             0.210         0.44             2.2      0.075   
661             7.5             0.420         0.31             1.6      0.080   
387             8.3             0.660         0.15             1.9      0.079   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
34                   13.0                  50.0  0.99570  3.38       0.55   
1580                  9.0                  26.0  0.99470  3.36       0.60   
786                  11.0                  61.0  0.99820  3.21       0.50   
1004                 27.0                  45.0  0.99603  3.25       0.54   
109                  37.0                 153.0  0.99690  3.21       0.69   
182                  16.0                  42.0  0.99720  3.44       0.52   
1435                 55.0                  95.0  1.00369  3.18       0.77   
243                  10.0                  24.0  1.00005  3.07       0.84   
661                  15.0                  42.0  0.99780  3.31       0.64   
387                  17.0                  42.0  0.99720  3.31       0.54   

      alcohol  
34        9.2  
1580     11.9  
786       9.5  
1004     10.3  
109       9.3  
182       9.3  
1435      9.0  
243       9.2  
661       9.0  
387       9.6

In [21]:
opf = open('regresiwine.pkl' , 'rb')
regres = pickle.load(opf)
y_pred = regres.predict(databr)

print(y_pred)

[5.28492351 6.27110501 5.43009359 5.67032746 4.7319683  4.97398339
 5.32471139 6.11967574 5.3005818  5.18897631]


C:\Users\ALIF RAMA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [22]:
#fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
databr=np.array([[6.8, 0.67 ,0.02 ,1.8 ,0.05 ,5 ,11 ,0.9962 ,3.48 ,0.52 ,9.5],
                [4.2, 0.41, 0.008, 1.2, 0.007, 4, 8, 0.6271, 2.81, 0.27, 7.3],
                [5.8, 0.59, 0.052, 2.1, 0.028, 6, 24, 1.3831, 3.19, 0.49, 8.2],
                [7.2, 3.81, 0.32, 4.1, 0.291, 9, 49, 3.9831, 4.21, 2.81, 12.8],
                [2.9, 1.61, 0.827, 2.8, 0.193, 7, 49, 2.9837, 2.49, 1.92, 4.7],
                [8.4, 5.81, 0.5, 5.2, 0.381, 14, 67, 4.7317, 5.19, 3.61, 6.1],
                [6.3, 4.92, 0.87, 6.1, 0.951, 5, 49, 5.9825, 7.56, 5.97, 7.2],
                [5.3, 7.29, 0.73, 5.8, 0.781, 7, 53, 4.7293, 5.89, 3.37, 6.7],
                [9.1, 14.7, 1.28, 7.92, 0.973, 9, 72, 4.0927, 8.39, 5.89, 9.7],
                [2.9, 5.2, 0.83, 5.82, 0.682, 5, 69, 3.8952, 4.42, 3.95, 7.3]])


In [23]:
opf = open('regresiwine.pkl' , 'rb')
regres = pickle.load(opf)
y_pred = regres.predict(databr)

print(y_pred)

[   5.18712007   16.43342134   -7.24759742  -90.26458303  -58.91743686
 -117.61843486 -155.31366607 -120.3647714  -106.61250373  -90.58414614]
